name: OpenWrt Config

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf config
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y install dos2unix
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
          
      - name: Clone source code
        run: |
          git clone https://github.com/coolsnowwolf/lede
          
      - name: Update feeds
        run: |
          cd lede
          sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
          echo >> feeds.conf.default
          echo 'src-git nas https://github.com/linkease/nas-packages.git;master' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Generate configuration file
        run: |
          cd lede
          rm -f ./.config*   
          make defconfig
        
      - name: Prepare artifact
        run: |
          mkdir config
          mv ./lede/.config ./config/config
          rm -rf lede
          cd config
          cp config config.txt
          unix2dos -ascii config.txt
          mv config.txt `date "+%Y-%m-%d-%H_%M_%S"`.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: config
          path: ./config/
     
      - name: Commit changes
        run: |
          git config --global user.email "ly88321@qq.com"
          git config --global user.name "ly88321"
          git add .
          git commit -m "默认配置文件" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
